language: python

git:
  quiet: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install espeak

matrix:
  include:
  - name: "Lint check"
    python: "3.6"
    install: pip install --quiet --upgrade cardboardlint pylint
    env: TEST_SUITE="lint"
  - name: "Unit tests"
    python: "3.6"
    install: pip install --quiet -r requirements_tests.txt
    env: TEST_SUITE="unittest"

script: ./.travis/script
